_commit: v2.3.0
_src_path: gh:mopidy/cookiecutter-mopidy-ext
author_email: alpetitjean@gmail.com
author_full_name: Alexandre Petitjean
dist_name: mopidy-somafm
ext_name: somafm
github_username: AlexandrePTJ
short_description: Mopidy extension for SomaFM
