sudo: false

language: python

python:
  - "2.7_with_system_site_packages"

addons:
  apt:
    sources:
      - mopidy-stable
    packages:
      - mopidy

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"

notifications:
  email:
    recipients:
      - alpetitjean@gmail.com
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
